name: Release

on:
  push:
    branches:
      - "main"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go run .

    - name: Tag next version
      run: |
        tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1) | awk -F. -v OFS=. '{$NF++;print}')
        git tag $tag

    - name: Release notes
      run: |
        git log $(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=2) | tail -1)..HEAD --pretty=format:"%h - %an: %s" > release-notes.txt
        cat release-notes.txt

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: List of Trust Lists
        body_path: release-notes.txt
        fail_on_unmatched_files: true
        files: |
          ltl.yaml
          ltl.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}