name: Release

on:
  push:
    branches:
      - "main"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go run .

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: List of Trust Lists
        fail_on_unmatched_files: true
        files: |
          ltl.yaml
          ltl.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}